448projectdir/everycheese/config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    path(
        "",
        TemplateView.as_view(template_name="pages/home.html"),
        name="home",
    ),
    path(
        "about/",
        TemplateView.as_view(template_name="pages/about.html"),
        name="about",
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path(
        "users/",
        include("everycheese.users.urls", namespace="users"),
    ),
    path("accounts/", include("allauth.urls")),
    path(
	'teams/',
	include('everycheese.nba.urls',
                namespace='teams',),
    ),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [
            path("__debug__/", include(debug_toolbar.urls))
        ] + urlpatterns

448projectdir/everycheese/everycheese/nba/urls.py
from django.urls import path
from . import views

app_name = "nba"
urlpatterns = [
    path(
        route='matches/', 
        view=views.MatchListView.as_view(), 
        name='match_list'
    ),
    path (
		route='',
		view=views.TeamListView.as_view(),
		name='team_list'
     ),
     path(
        route='matches/<slug:slug>/', 
        view=views.MatchDetailView.as_view(), 
        name='match_detail'
    ),
    path (
        route='<slug:slug>',
        view=views.TeamDetailView.as_view(),
        name='team_detail'
	)
]

448projectdir/everycheese/everycheese/users/urls.py
from django.urls import path

from everycheese.users.views import (
    user_redirect_view,
    user_update_view,
    user_detail_view,
    user_list_view,
)

app_name = "users"
urlpatterns = [
    path(
        route = "users/",
        view=user_list_view,
        name="user_list"
    ),
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

448projectdir/everycheese/everycheese/nba/models.py
from django.db import models
from autoslug import AutoSlugField
from model_utils.models import TimeStampedModel
from django.urls import reverse
from django.conf import settings



class Team(TimeStampedModel):
    team_name = models.CharField("Team Name", max_length=255)
    slug = AutoSlugField("Team Address", unique=True, always_update=False, populate_from="team_name")
    created_date = models.DateField("Date Created:", blank=True)
    points = models.IntegerField("Points:", blank=True, null=True)
    standings = models.CharField("Standing:", max_length=10, blank=True, null=True)
    avg_assists = models.IntegerField("Average Assists:", blank=True, null=True)
    avg_rebounds = models.IntegerField("Average Rebounds:", blank=True, null=True)
    avg_shootings = models.IntegerField("Average Shootings:", blank=True, null=True)


    def __str__(self):
        return self.team_name

    def get_absolute_url(self):
        return reverse('nba:team_detail', kwargs={"slug": self.slug})

class Match(TimeStampedModel):
    match_name = models.CharField("Match Name", max_length=255)
    slug = AutoSlugField("Match Address", unique=True, always_update=False, populate_from="match_name")
    match_date = models.DateField("Match Date", blank=True)
    winner_id = models.ForeignKey(Team, on_delete=models.CASCADE, related_name='won_matches', null=True, blank=True)
    created_date = models.DateField("Date Created:", blank=True)
    team1_assists = models.IntegerField("Team 1 Assists", default=0)
    team2_assists = models.IntegerField("Team 2 Assists", default=0)
    team1_rebounds = models.IntegerField("Team 1 Rebounds", default=0)
    team2_rebounds = models.IntegerField("Team 2 Rebounds", default=0)
    team1_shooting = models.IntegerField("Team 1 Shooting", default=0)
    team2_shooting = models.IntegerField("Team 2 Shooting", default=0)
    score = models.CharField("Score", max_length=255, blank=True, null=True)
    
    def __str__(self):
        return self.match_name


   

448projectdir/everycheese/everycheese/users/models.py
from django.contrib.auth.models import AbstractUser
from everycheese.nba.models import Team
from django.db import models
from django.urls import reverse
from autoslug import AutoSlugField
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):

    # First Name and Last Name Do Not Cover Name Patterns
    # Around the Globe.
    name = models.CharField(
        _("Name of User"), blank=True, max_length=255
    )


    team = models.ForeignKey(Team, on_delete=models.CASCADE, null=True)
    
    slug = AutoSlugField("User Address", unique=True, always_update=False, populate_from="name", null=True)

    def get_absolute_url(self):
        return reverse(
            "users:detail", kwargs={"username": self.username}
        )

448projectdir/everycheese/everycheese/users/forms.py
from django.contrib.auth import get_user_model, forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):
    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {
            "duplicate_username": _(
                "This username has already been taken."
            )
        }
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(
            self.error_messages["duplicate_username"]
        )

448projectdir/everycheese/everycheese/nba/views.py
from django.views.generic import ListView, DetailView, UpdateView

from .models import Team, Match

from everycheese.users.models import User

from django.contrib.auth.mixins import LoginRequiredMixin

class TeamListView(ListView):
	model = Team

class MatchListView(ListView):
    model = Match

class MatchDetailView(DetailView):
    model = Match

class TeamDetailView(DetailView):
	model = Team

class TeamUpdateView(UpdateView):
	model = User

	fields = [
		'team',
	]
	
	action = "Update"

	def form_valid(self, form):
		form.instance.creator = self.request.user
		return super().form_valid(form)

448projectdir/everycheese/everycheese/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import (
    ListView,
    DetailView,
    RedirectView,
    UpdateView,
)

User = get_user_model()

class UserListView(ListView):
	model = User

	ordering = "-team__points"

user_list_view = UserListView.as_view()


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These Next Two Lines Tell the View to Index
    #   Lookups by Username
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):
    fields = [
        "name",
	"team",
    ]

    # We already imported user in the View code above,
    #   remember?
    model = User

    # Send the User Back to Their Own Page after a
    #   successful Update
    def get_success_url(self):
        return reverse(
            "users:detail",
            kwargs={'username': self.request.user.username},
        )

    def get_object(self):
        # Only Get the User Record for the
        #   User Making the Request
        return User.objects.get(
            username=self.request.user.username
        )


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse(
            "users:detail",
            kwargs={"username": self.request.user.username},
        )


user_redirect_view = UserRedirectView.as_view()

448projectdir/everycheese/everycheese/templates/base.html
{% load static i18n %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}EveryCheese{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">

    {% block css %}
    <!-- Latest compiled and minified Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!-- Your stuff: Third-party CSS libraries go here -->
    <!-- This file stores project-specific CSS -->

    <link href="{% static 'css/project.css' %}" rel="stylesheet">
    {% endblock %}

  </head>

  <body>

    <div class="mb-1">
      <nav class="navbar navbar-expand-md navbar-dark #0d1217 navbar-text #0d1217;">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'home' %}">NBA Fantasy</a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
	    <li class="nav-item">
	      <a class="nav-link" href="{% url 'nba:team_list' %}">Teams</a>
	    </li>
      <li class="nav-item">
	      <a class="nav-link" href="{% url 'nba:match_list' %}">Matches</a>
	    </li>
      <li class="nav-item">
	      <a class="nav-link" href="{% url 'users:user_list' %}">Rankings</a>
	    </li>
            {% if request.user.is_authenticated %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
              </li>
            {% else %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </nav>

    </div>

    <div class="container">

      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>
          {% endfor %}
      {% endif %}

      {% block content %}
      <div class="box">
      <h1>Welcome to Fantasy NBA</h1>
<p>Experience the thrill of managing your own NBA fantasy team!</p>

<div style="position:relative;width:100%;padding-top:40%;margin-top:1.6em;margin-bottom:0.9em;overflow:hidden;border-radius:8px;will-change:transform;">
  <iframe loading="eager" style="position:absolute;width:100%;height:100%;top:0;left:0;border:none;padding:0;margin:0;"
    src="https://www.canva.com/design/DAGB1YdHR7A/lNz6BtiUBdOvITRgCBPVSQ/view?embed" controls = "0">
  </iframe>
</div>
</div>
<div class="box">
<h2>Join the Action</h2>
<p>Sign up now to start drafting your dream team, compete with friends, and climb the ranks to become the ultimate fantasy basketball champion. Get Started Today</p>
<div style="position:relative;width:100%;padding-top:40%;margin-top:1.6em;margin-bottom:0.9em;overflow:hidden;border-radius:8px;will-change:transform;">
  <iframe loading="eager" style="position:absolute;width:100%;height:100%;top:0;left:0;border:none;padding:0;margin:0;"
    src="https://www.canva.com/design/DAGB1v9Cknc/-w-YZhdTkFKqcDnI_d8UeQ/view?embed" controls="0">
  </iframe>
</div>
</div>
<div class="box">
<h3>Get Started Today</h3>
<p>Join thousands of basketball fans who are already enjoying the excitement of fantasy NBA. Sign up now and let the games begin!</p>
<div style="position:relative;width:100%;padding-top:40%;margin-top:1.6em;margin-bottom:0.9em;overflow:hidden;border-radius:8px;will-change:transform;">
  <iframe loading="eager" style="position:absolute;width:100%;height:100%;top:0;left:0;border:none;padding:0;margin:0;"
    src="https://www.canva.com/design/DAGB1m8MYJc/cDtDm85Txe9zI2wkUC-nWw/view?embed" controls="0">
  </iframe>
</div>
</div>
<div style="height: 100px;"></div>

{% endblock content %}

    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}
      <!-- Bootstrap JS and its dependencies-->
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

      <!-- Your stuff: Third-party javascript libraries go here -->


      <!-- place project specific Javascript in this file -->
      <script src="{% static 'js/project.js' %}"></script>
    {% endblock javascript %}
  </body>
</html>