448projectdir/everycheese/config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    path(
        "",
        TemplateView.as_view(template_name="pages/home.html"),
        name="home",
    ),
    path(
        "about/",
        TemplateView.as_view(template_name="pages/about.html"),
        name="about",
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path(
        "users/",
        include("everycheese.users.urls", namespace="users"),
    ),
    path("accounts/", include("allauth.urls")),
    path(
	'teams/',
	include('everycheese.nba.urls',
                namespace='teams',),
    ),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [
            path("__debug__/", include(debug_toolbar.urls))
        ] + urlpatterns

448projectdir/everycheese/everycheese/nba/urls.py
from django.urls import path
from . import views

app_name = "nba"
urlpatterns = [
    path(
        route='matches/', 
        view=views.MatchListView.as_view(), 
        name='match_list'
    ),
    path (
		route='',
		view=views.TeamListView.as_view(),
		name='team_list'
     ),
     path(
        route='matches/<slug:slug>/', 
        view=views.MatchDetailView.as_view(), 
        name='match_detail'
    ),
    path (
        route='<slug:slug>',
        view=views.TeamDetailView.as_view(),
        name='team_detail'
	)
]

448projectdir/everycheese/everycheese/users/urls.py
from django.urls import path

from everycheese.users.views import (
    user_redirect_view,
    user_update_view,
    user_detail_view,
    user_list_view,
)

app_name = "users"
urlpatterns = [
    path(
        route = "users/",
        view=user_list_view,
        name="user_list"
    ),
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

448projectdir/everycheese/everycheese/nba/models.py
from django.db import models
from autoslug import AutoSlugField
from model_utils.models import TimeStampedModel
from django.urls import reverse
from django.conf import settings



class Team(TimeStampedModel):
    team_name = models.CharField("Team Name", max_length=255)
    slug = AutoSlugField("Team Address", unique=True, always_update=False, populate_from="team_name")
    created_date = models.DateField("Date Created:", blank=True)
    points = models.IntegerField("Points:", blank=True, null=True)
    standings = models.CharField("Standing:", max_length=10, blank=True, null=True)
    avg_assists = models.IntegerField("Average Assists:", blank=True, null=True)
    avg_rebounds = models.IntegerField("Average Rebounds:", blank=True, null=True)
    avg_shootings = models.IntegerField("Average Shootings:", blank=True, null=True)


    def __str__(self):
        return self.team_name

    def get_absolute_url(self):
        return reverse('nba:team_detail', kwargs={"slug": self.slug})

class Match(TimeStampedModel):
    match_name = models.CharField("Match Name", max_length=255)
    slug = AutoSlugField("Match Address", unique=True, always_update=False, populate_from="match_name")
    match_date = models.DateField("Match Date", blank=True)
    winner_id = models.ForeignKey(Team, on_delete=models.CASCADE, related_name='won_matches', null=True, blank=True)
    created_date = models.DateField("Date Created:", blank=True)
    team1_assists = models.IntegerField("Team 1 Assists", default=0)
    team2_assists = models.IntegerField("Team 2 Assists", default=0)
    team1_rebounds = models.IntegerField("Team 1 Rebounds", default=0)
    team2_rebounds = models.IntegerField("Team 2 Rebounds", default=0)
    team1_shooting = models.IntegerField("Team 1 Shooting", default=0)
    team2_shooting = models.IntegerField("Team 2 Shooting", default=0)
    score = models.CharField("Score", max_length=255, blank=True, null=True)
    
    def __str__(self):
        return self.match_name


   

448projectdir/everycheese/everycheese/users/models.py
from django.contrib.auth.models import AbstractUser
from everycheese.nba.models import Team
from django.db import models
from django.urls import reverse
from autoslug import AutoSlugField
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):

    # First Name and Last Name Do Not Cover Name Patterns
    # Around the Globe.
    name = models.CharField(
        _("Name of User"), blank=True, max_length=255
    )


    team = models.ForeignKey(Team, on_delete=models.CASCADE, null=True)
    
    slug = AutoSlugField("User Address", unique=True, always_update=False, populate_from="name", null=True)

    def get_absolute_url(self):
        return reverse(
            "users:detail", kwargs={"username": self.username}
        )

448projectdir/everycheese/everycheese/users/forms.py
from django.contrib.auth import get_user_model, forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):
    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {
            "duplicate_username": _(
                "This username has already been taken."
            )
        }
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(
            self.error_messages["duplicate_username"]
        )

448projectdir/everycheese/everycheese/nba/views.py
from django.views.generic import ListView, DetailView, UpdateView

from .models import Team, Match

from everycheese.users.models import User

from django.contrib.auth.mixins import LoginRequiredMixin

class TeamListView(ListView):
	model = Team

class MatchListView(ListView):
    model = Match

class MatchDetailView(DetailView):
    model = Match

class TeamDetailView(DetailView):
	model = Team

class TeamUpdateView(UpdateView):
	model = User

	fields = [
		'team',
	]
	
	action = "Update"

	def form_valid(self, form):
		form.instance.creator = self.request.user
		return super().form_valid(form)

448projectdir/everycheese/everycheese/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import (
    ListView,
    DetailView,
    RedirectView,
    UpdateView,
)

User = get_user_model()

class UserListView(ListView):
	model = User

	ordering = "-team__points"

user_list_view = UserListView.as_view()


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These Next Two Lines Tell the View to Index
    #   Lookups by Username
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):
    fields = [
        "name",
	"team",
    ]

    # We already imported user in the View code above,
    #   remember?
    model = User

    # Send the User Back to Their Own Page after a
    #   successful Update
    def get_success_url(self):
        return reverse(
            "users:detail",
            kwargs={'username': self.request.user.username},
        )

    def get_object(self):
        # Only Get the User Record for the
        #   User Making the Request
        return User.objects.get(
            username=self.request.user.username
        )


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse(
            "users:detail",
            kwargs={"username": self.request.user.username},
        )


user_redirect_view = UserRedirectView.as_view()

448projectdir/everycheese/everycheese/templates/nba/match_detail.html
{% extends "base.html" %}

{% block title %}NBA Matches: {{match.match_name }} {% endblock title %}

{% block content %}
<div class="box">
    <h2>{{ match.match_name }}</h2>

    {% if match.match_date %}
        <p>Match Date: {{ match.match_date }}</p>
    {% endif %}

    {% if match.winner_id %}
        <p>Winner: {{ match.winner_id }}</p>
    {% endif %}
    <div style="position: relative; width: 100%; height: 0; padding-top: 40%;
 padding-bottom: 0; box-shadow: 0 2px 8px 0 rgba(63,69,81,0.16); margin-top: 1.6em; margin-bottom: 0.9em; overflow: hidden;
 border-radius: 8px; will-change: transform;">
  <iframe loading="eager" style="position: absolute; width: 100%; height: 100%; top: 0; left: 0; border: none; padding: 0;margin: 0;"
    src="https:&#x2F;&#x2F;www.canva.com&#x2F;design&#x2F;DAGDPWQRpAk&#x2F;telPwUo7fD-a-Wk9qTyQ0w&#x2F;view?embed">
  </iframe>
</div>
    {% if match.score %}
        <p>Game Score: {{ match.score }}</p>
    {% endif %}
    </div>

    <div class="box">
    <h4>{{ match.team_id1 }} Stats:</h4>
    {% if match.team1_assists %}
    <p>Assists: {{ match.team1_assists}}</p>
{% endif %}
<div style="position: relative; width: 100%; height: 0; padding-top: 40%; padding-bottom: 0; box-shadow: 0 2px 8px 0 rgba(63,69,81,0.16); margin-top: 1.6em; margin-bottom: 0.9em; overflow: hidden;
 border-radius: 8px; will-change: transform;">
  <iframe loading="eager" style="position: absolute; width: 100%; height: 100%; top: 0; left: 0; border: none; padding: 0;margin: 0;"
    src="https:&#x2F;&#x2F;www.canva.com&#x2F;design&#x2F;DAGDPUcWDzk&#x2F;wb7wJlSBqnXtH0ssyWaAgQ&#x2F;view?embed">
  </iframe>
</div>
{% if match.team1_rebounds %}
    <p>Rebounds: {{ match.team1_rebounds}}</p>
{% endif %}
<div style="position: relative; width: 100%; height: 0; padding-top: 40%;
 padding-bottom: 0; box-shadow: 0 2px 8px 0 rgba(63,69,81,0.16); margin-top: 1.6em; margin-bottom: 0.9em; overflow: hidden;
 border-radius: 8px; will-change: transform;">
  <iframe loading="eager" style="position: absolute; width: 100%; height: 100%; top: 0; left: 0; border: none; padding: 0;margin: 0;"
    src="https:&#x2F;&#x2F;www.canva.com&#x2F;design&#x2F;DAGDPQg-N7A&#x2F;vk1oFGWQky8IXqn4jfpitw&#x2F;view?embed">
  </iframe>
</div>
{% if match.team1_shooting %}
    <p>Field Goal Percentage: {{ match.team1_shooting}}%</p>
{% endif %}
<div style="position: relative; width: 100%; height: 0; padding-top: 40%;
 padding-bottom: 0; box-shadow: 0 2px 8px 0 rgba(63,69,81,0.16); margin-top: 1.6em; margin-bottom: 0.9em; overflow: hidden;
 border-radius: 8px; will-change: transform;">
  <iframe loading="eager" style="position: absolute; width: 100%; height: 100%; top: 0; left: 0; border: none; padding: 0;margin: 0;"
    src="https:&#x2F;&#x2F;www.canva.com&#x2F;design&#x2F;DAGDPQNqiQQ&#x2F;-LllvqTQvCSlWmulZgSJug&#x2F;view?embed">
  </iframe>
</div>
    </div>

    <div class="box">
<h4>{{ match.team_id2 }} Stats:</h4>
{% if match.team2_assists %}
    <p>Assists: {{ match.team2_assists}}</p>
{% endif %}
<div style="position: relative; width: 100%; height: 0; padding-top: 40%; padding-bottom: 0; box-shadow: 0 2px 8px 0 rgba(63,69,81,0.16); margin-top: 1.6em; margin-bottom: 0.9em; overflow: hidden;
 border-radius: 8px; will-change: transform;">
  <iframe loading="eager" style="position: absolute; width: 100%; height: 100%; top: 0; left: 0; border: none; padding: 0;margin: 0;"
    src="https:&#x2F;&#x2F;www.canva.com&#x2F;design&#x2F;DAGDPUcWDzk&#x2F;wb7wJlSBqnXtH0ssyWaAgQ&#x2F;view?embed">
  </iframe>
</div>
{% if match.team2_rebounds %}
    <p>Rebounds: {{ match.team2_rebounds}}</p>
{% endif %}
<div style="position: relative; width: 100%; height: 0; padding-top: 40%;
 padding-bottom: 0; box-shadow: 0 2px 8px 0 rgba(63,69,81,0.16); margin-top: 1.6em; margin-bottom: 0.9em; overflow: hidden;
 border-radius: 8px; will-change: transform;">
  <iframe loading="eager" style="position: absolute; width: 100%; height: 100%; top: 0; left: 0; border: none; padding: 0;margin: 0;"
    src="https:&#x2F;&#x2F;www.canva.com&#x2F;design&#x2F;DAGDPQg-N7A&#x2F;vk1oFGWQky8IXqn4jfpitw&#x2F;view?embed">
  </iframe>
</div>
{% if match.team2_shooting %}
    <p>Field Goal Percentage: {{ match.team2_shooting}}%</p>
{% endif %}
<div style="position: relative; width: 100%; height: 0; padding-top: 40%;
 padding-bottom: 0; box-shadow: 0 2px 8px 0 rgba(63,69,81,0.16); margin-top: 1.6em; margin-bottom: 0.9em; overflow: hidden;
 border-radius: 8px; will-change: transform;">
  <iframe loading="eager" style="position: absolute; width: 100%; height: 100%; top: 0; left: 0; border: none; padding: 0;margin: 0;"
    src="https:&#x2F;&#x2F;www.canva.com&#x2F;design&#x2F;DAGDPQNqiQQ&#x2F;-LllvqTQvCSlWmulZgSJug&#x2F;view?embed">
  </iframe>
</div>
    </div>

{% endblock content %}

448projectdir/everycheese/everycheese/templates/nba/match_list.html
{% extends "base.html" %}

{% block title %}
  NBA Matches
{% endblock %}

{% block content %}
<div class="box">
  <h2>NBA Matches</h2>
  <div style="position: relative; width: 100%; height: 0; padding-top: 40%; padding-bottom: 0; box-shadow: 0 2px 8px 0 rgba(63,69,81,0.16); margin-top: 1.6em; margin-bottom: 0.9em; overflow: hidden; border-radius: 8px; will-change: transform;">
	<iframe loading="eager" style="position: absolute; width: 100%; height: 100%; top: 0; left: 0; border: none; padding: 0; margin: 0;" src="https://www.canva.com/design/DAGDDbRMF-A/Rlbh-N5C9dejMcUVZNGb5w/view?embed"></iframe>
  </div>
  <p>Here under matches, see the latest games that your team has played!
    Also, dig into the stats of the game to see if your team won so you can get a clue on where you might stand in the weekly rankings!</p>
</div>
<div class="box">
  <ul>
    {% for match in match_list %}
      <li><a href="{% url 'nba:match_detail' match.slug %}">{{ match.match_name }}</a></li>
    {% endfor %}
  </ul>
</div>
{% endblock %}

448projectdir/everycheese/everycheese/templates/nba/team_detail.html
{% extends "base.html" %}

{% block title %}NBA Teams: {{team.team_name }} {% endblock title %}

{% block content %}
<div class="box">
    <h2>{{ team.team_name }}</h2>
    {% if team.standings %}
    <p>Team Standings: {{ team.standings }}</p>
    <div style="position: relative; width: 100%; height: 0; padding-top: 40%;
 padding-bottom: 0; box-shadow: 0 2px 8px 0 rgba(63,69,81,0.16); margin-top: 1.6em; margin-bottom: 0.9em; overflow: hidden;
 border-radius: 8px; will-change: transform;">
  <iframe loading="eager" style="position: absolute; width: 100%; height: 100%; top: 0; left: 0; border: none; padding: 0;margin: 0;"
    src="https:&#x2F;&#x2F;www.canva.com&#x2F;design&#x2F;DAGDiv_HgEk&#x2F;FHn2OChSbuRhqrliAYqDvA&#x2F;view?embed">
  </iframe>
</div>
{% endif %}

    {% if team.avg_assists %}
    <p>Assists: {{ team.avg_assists}}</p>
{% endif %}
<div style="position: relative; width: 100%; height: 0; padding-top: 40%; padding-bottom: 0; box-shadow: 0 2px 8px 0 rgba(63,69,81,0.16); margin-top: 1.6em; margin-bottom: 0.9em; overflow: hidden;
 border-radius: 8px; will-change: transform;">
  <iframe loading="eager" style="position: absolute; width: 100%; height: 100%; top: 0; left: 0; border: none; padding: 0;margin: 0;"
    src="https:&#x2F;&#x2F;www.canva.com&#x2F;design&#x2F;DAGDPUcWDzk&#x2F;wb7wJlSBqnXtH0ssyWaAgQ&#x2F;view?embed">
  </iframe>
</div>
{% if team.avg_rebounds %}
    <p>Rebounds: {{ team.avg_rebounds}}</p>
{% endif %}
<div style="position: relative; width: 100%; height: 0; padding-top: 40%;
 padding-bottom: 0; box-shadow: 0 2px 8px 0 rgba(63,69,81,0.16); margin-top: 1.6em; margin-bottom: 0.9em; overflow: hidden;
 border-radius: 8px; will-change: transform;">
  <iframe loading="eager" style="position: absolute; width: 100%; height: 100%; top: 0; left: 0; border: none; padding: 0;margin: 0;"
    src="https:&#x2F;&#x2F;www.canva.com&#x2F;design&#x2F;DAGDPQg-N7A&#x2F;vk1oFGWQky8IXqn4jfpitw&#x2F;view?embed">
  </iframe>
</div>
{% if team.avg_shootings %}
    <p>Field Goal Percentage: {{ team.avg_shootings}}%</p>
{% endif %}
<div style="position: relative; width: 100%; height: 0; padding-top: 40%;
 padding-bottom: 0; box-shadow: 0 2px 8px 0 rgba(63,69,81,0.16); margin-top: 1.6em; margin-bottom: 0.9em; overflow: hidden;
 border-radius: 8px; will-change: transform;">
  <iframe loading="eager" style="position: absolute; width: 100%; height: 100%; top: 0; left: 0; border: none; padding: 0;margin: 0;"
    src="https:&#x2F;&#x2F;www.canva.com&#x2F;design&#x2F;DAGDPQNqiQQ&#x2F;-LllvqTQvCSlWmulZgSJug&#x2F;view?embed">
  </iframe>
</div>
    </div>
{% endblock content %}

448projectdir/everycheese/everycheese/templates/nba/team_form.html
{% extends "base.html" %}
{% block title %}Join a Team{% endblock title %}
{% block content %}
<h1>Join a Team</h1>
<form method="post" action="{% url 'nba:add' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Join</button>
</form>
{% endblock content %}

448projectdir/everycheese/everycheese/templates/nba/team_list.html
{% extends "base.html" %}

{% block title %}
  NBA Teams
{% endblock %}

{% block content %}
<div class="box">
  <h2>NBA Teams</h2>
    <div style="position: relative; width: 100%; height: 0; padding-top: 40%; padding-bottom: 0; box-shadow: 0 2px 8px 0 rgba(63,69,81,0.16); margin-top: 1.6em; margin-bottom: 0.9em; overflow: hidden;
 border-radius: 8px; will-change: transform;">
  <iframe loading="eager" style="position: absolute; width: 100%; height: 100%; top: 0; left: 0; border: none; padding: 0;margin: 0;"
    src="https:&#x2F;&#x2F;www.canva.com&#x2F;design&#x2F;DAGDJqBWyDU&#x2F;Bq03qya93msqFHcxJo1OVQ&#x2F;view?embed">
  </iframe>
</div>
  <ul>
    {% for team in team_list %}
      <li><a href="{% url 'nba:team_detail' team.slug %}">{{ team.team_name }}</a></li>
    {% endfor %}
  </ul>
</div>
<div class="box">
  <h2>Pick a Team?</h2>
  <p>Want to pick a team click this button</p>
  <a class="btn btn-primary" href="{% url 'users:update' %}" role="button">Update</a>
</div>


{% endblock %}